// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmcb2_1g31Tg1a5USFWZPBpcuGSEzIVZA',
    appId: '1:590832914506:web:5b9836f356a6907f8796b3',
    messagingSenderId: '590832914506',
    projectId: 'pakashiyana',
    authDomain: 'pakashiyana.firebaseapp.com',
    storageBucket: 'pakashiyana.firebasestorage.app',
    measurementId: 'G-T99LJRL7BB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv0np2pkya0FTuqP7TAwKJjloXfReuQSU',
    appId: '1:590832914506:ios:d1c74c97aaee1c408796b3',
    messagingSenderId: '590832914506',
    projectId: 'pakashiyana',
    storageBucket: 'pakashiyana.firebasestorage.app',
    iosBundleId: 'com.example.pakashiyana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmcb2_1g31Tg1a5USFWZPBpcuGSEzIVZA',
    appId: '1:590832914506:web:086803d137feb78d8796b3',
    messagingSenderId: '590832914506',
    projectId: 'pakashiyana',
    authDomain: 'pakashiyana.firebaseapp.com',
    storageBucket: 'pakashiyana.firebasestorage.app',
    measurementId: 'G-W8E7XZ0L5M',
  );
}
